[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "drh-target"
version = "0.1.0"
dependencies = []

[tool.setuptools.package-data]
"drh_target.schemas" = ["*.json"]